// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	pb/auth.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
	User
	Profile
	Province
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the username and password.
type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// The response message containing the JWT token.
type LoginResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	User  *User  `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// The user message containing the user.
type User struct {
	Id           uint32     `protobuf:"varint,1,opt,name=id" json:"omitempty"`
	Email        string     `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Username     string     `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	PasswordHash string     `protobuf:"bytes,4,opt,name=passwordHash" json:"-"`
	Profile      []*Profile `protobuf:"bytes,5,rep,name=profile" json:"profile,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *User) GetProfile() []*Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type Profile struct {
	Id        uint32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Avatar    string    `protobuf:"bytes,2,opt,name=avatar" json:"avatar,omitempty"`
	Firstname string    `protobuf:"bytes,3,opt,name=firstname" json:"firstname,omitempty"`
	Lastname  string    `protobuf:"bytes,4,opt,name=lastname" json:"lastname,omitempty"`
	Birthdate string    `protobuf:"bytes,5,opt,name=birthdate" json:"birthdate,omitempty"`
	Sex       uint32    `protobuf:"varint,6,opt,name=sex" json:"sex,omitempty"`
	Province  *Province `protobuf:"bytes,7,opt,name=province" json:"province,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Profile) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Profile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Profile) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Profile) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Profile) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *Profile) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Profile) GetProvince() *Province {
	if m != nil {
		return m.Province
	}
	return nil
}

type Province struct {
	ProvinceId   uint32 `protobuf:"varint,1,opt,name=provinceId" json:"provinceId,omitempty"`
	ProvinceName string `protobuf:"bytes,2,opt,name=provinceName" json:"provinceName,omitempty"`
}

func (m *Province) Reset()                    { *m = Province{} }
func (m *Province) String() string            { return proto.CompactTextString(m) }
func (*Province) ProtoMessage()               {}
func (*Province) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Province) GetProvinceId() uint32 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *Province) GetProvinceName() string {
	if m != nil {
		return m.ProvinceName
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*Profile)(nil), "auth.Profile")
	proto.RegisterType((*Province)(nil), "auth.Province")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/auth.Auth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/auth.proto",
}

func init() { proto.RegisterFile("pb/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4d, 0xae, 0xd3, 0x30,
	0x14, 0x85, 0x95, 0x34, 0xfd, 0xbb, 0x6d, 0x2a, 0xe4, 0x22, 0x14, 0xaa, 0xaa, 0xaa, 0x3c, 0xa1,
	0xea, 0xa0, 0x11, 0x65, 0xc6, 0x8c, 0x01, 0x08, 0x04, 0xaa, 0x50, 0x10, 0x0b, 0x70, 0x89, 0xdb,
	0x58, 0xa4, 0x76, 0xb0, 0x9d, 0xc2, 0x98, 0x2d, 0x20, 0xd6, 0xc4, 0x02, 0xd8, 0x02, 0x0b, 0x41,
	0xfe, 0x49, 0x5e, 0xfa, 0xde, 0xcc, 0xe7, 0x1c, 0xdf, 0xeb, 0xcf, 0x57, 0x17, 0xe2, 0xea, 0x98,
	0x92, 0x5a, 0x17, 0xbb, 0x4a, 0x0a, 0x2d, 0x50, 0x64, 0xce, 0x8b, 0xe5, 0x59, 0x88, 0x73, 0x49,
	0x53, 0x52, 0xb1, 0x94, 0x70, 0x2e, 0x34, 0xd1, 0x4c, 0x70, 0xe5, 0xee, 0xe0, 0x37, 0x30, 0xfd,
	0x20, 0xce, 0x8c, 0x67, 0xf4, 0x5b, 0x4d, 0x95, 0x46, 0x0b, 0x18, 0xd5, 0x8a, 0x4a, 0x4e, 0x2e,
	0x34, 0x09, 0xd6, 0xc1, 0x66, 0x9c, 0xb5, 0xda, 0x64, 0x15, 0x51, 0xea, 0xbb, 0x90, 0x79, 0x12,
	0xba, 0xac, 0xd1, 0xf8, 0x35, 0xc4, 0xbe, 0x8f, 0xaa, 0x04, 0x57, 0x14, 0x3d, 0x86, 0xbe, 0x16,
	0x5f, 0x29, 0xf7, 0x5d, 0x9c, 0x40, 0x2b, 0x88, 0x4c, 0x3b, 0x5b, 0x3e, 0xd9, 0xc3, 0xce, 0xd2,
	0x7e, 0x56, 0x54, 0x66, 0xd6, 0xc7, 0xbf, 0x03, 0x88, 0x8c, 0x44, 0x33, 0x08, 0x59, 0x6e, 0x6b,
	0xe3, 0x2c, 0x64, 0xb9, 0x69, 0x47, 0x2f, 0x84, 0x95, 0xfe, 0x61, 0x27, 0x6e, 0x68, 0x7b, 0xf7,
	0x68, 0x31, 0x4c, 0x1b, 0xba, 0xb7, 0x44, 0x15, 0x49, 0x64, 0xf3, 0x1b, 0x0f, 0x3d, 0x83, 0x61,
	0x25, 0xc5, 0x89, 0x95, 0x34, 0xe9, 0xaf, 0x7b, 0x9b, 0xc9, 0x3e, 0x76, 0x44, 0x1f, 0x9d, 0x99,
	0x35, 0x29, 0xfe, 0x13, 0xc0, 0xd0, 0x9b, 0x0f, 0xd0, 0x9e, 0xc0, 0x80, 0x5c, 0x89, 0x26, 0xd2,
	0xb3, 0x79, 0x85, 0x96, 0x30, 0x3e, 0x31, 0xa9, 0x74, 0x87, 0xee, 0xce, 0x30, 0xe8, 0x25, 0xf1,
	0xa1, 0x43, 0x6b, 0xb5, 0xa9, 0x3c, 0x32, 0xa9, 0x8b, 0x9c, 0x68, 0x03, 0x66, 0x2b, 0x5b, 0x03,
	0x3d, 0x82, 0x9e, 0xa2, 0x3f, 0x92, 0x81, 0x05, 0x30, 0x47, 0xb4, 0x85, 0x51, 0x25, 0xc5, 0x95,
	0xf1, 0x2f, 0x34, 0x19, 0xda, 0xc9, 0xce, 0xda, 0x7f, 0x58, 0x37, 0x6b, 0x73, 0x7c, 0x80, 0x51,
	0xe3, 0xa2, 0x15, 0x40, 0xe3, 0xbf, 0x6b, 0x7e, 0xd4, 0x71, 0xec, 0x08, 0xbd, 0x3a, 0x18, 0xce,
	0xd0, 0x8f, 0xb0, 0xe3, 0xed, 0x3f, 0x41, 0xf4, 0xaa, 0xd6, 0x05, 0x7a, 0x0f, 0x7d, 0xbb, 0x00,
	0x08, 0xb9, 0xa7, 0xbb, 0x5b, 0xb5, 0x98, 0xdf, 0x78, 0x6e, 0x43, 0xf0, 0xd3, 0x9f, 0x7f, 0xff,
	0xfd, 0x0a, 0xe7, 0x78, 0x96, 0x5e, 0x9f, 0xdb, 0xb5, 0x4d, 0x4b, 0x93, 0xbf, 0x0c, 0xb6, 0xc7,
	0x81, 0x5d, 0xce, 0x17, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x78, 0xdc, 0x9c, 0x80, 0xd1, 0x02,
	0x00, 0x00,
}
